# Generated by Django 3.1.2 on 2021-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Login', '0004_auto_20210109_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('Carpinteria', 'Carpinteria'), ('Pintura', 'Pintura'), ('Electricidad', 'Electricidad'), ('Herreria', 'Herreria'), ('Limpieza', 'Limpieza'), ('Plomeria', 'Plomeria'), ('Jardineria', 'Jardineria')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
