# Generated by Django 3.1.2 on 2021-01-25 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_auto_20210124_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='municipio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Login.municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Login.provincia'),
            preserve_default=False,
        ),
    ]
