# Generated by Django 3.1.2 on 2021-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_auto_20210125_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='text',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
