# Generated by Django 3.1.2 on 2021-01-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_municipio_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='text',
        ),
    ]
