# Generated by Django 3.1.2 on 2021-01-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_remove_municipio_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('linkFaceBook', models.CharField(blank=True, max_length=50, null=True)),
                ('linkTwitter', models.CharField(blank=True, max_length=50, null=True)),
                ('linkIG', models.CharField(blank=True, max_length=50, null=True)),
                ('linkLinkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.user')),
            ],
        ),
    ]
