# Generated by Django 3.1.6 on 2021-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0019_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
