# Generated by Django 3.1.6 on 2021-02-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0020_notificacion_leido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
