# Generated by Django 3.1.6 on 2021-02-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0022_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
