# Generated by Django 3.1.6 on 2021-02-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0023_delete_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.user')),
            ],
        ),
    ]
