# Generated by Django 3.1.2 on 2021-01-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'permissions': [('Carpinteria', 'Carpinteria'), ('Pintura', 'Pintura'), ('Electricidad', 'Electricidad'), ('Herreria', 'Herreria'), ('Limpieza', 'Limpieza'), ('Plomeria', 'Plomeria'), ('Jardineria', 'Jardineria')]},
        ),
    ]
