# Generated by Django 3.1.2 on 2021-01-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesional', '0002_auto_20210110_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={},
        ),
    ]
