# Generated by Django 3.1.2 on 2021-01-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20210112_1151'),
        ('Profesional', '0003_auto_20210110_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.user'),
        ),
    ]
