# Generated by Django 3.1.2 on 2021-01-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesional', '0004_auto_20210112_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='valoracion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
