# Generated by Django 3.1.2 on 2021-01-06 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OficinaCliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trabajos_realizados', models.IntegerField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('Carpinteria', 'Carpinteria'), ('Pintura', 'Pintura'), ('Electricidad', 'Electricidad'), ('Herreria', 'Herreria'), ('Limpieza', 'Limpieza'), ('Plomeria', 'Plomeria'), ('Jardineria', 'Jardineria'), ('Recoleccion de basura', 'Recoleccion de basura')],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('FechaDeEntrada', models.DateTimeField(auto_now_add=True)),
                ('FechaLimite', models.DateTimeField()),
                ('cliente_TrabajoTerminado', models.BooleanField(default=False)),
                ('profesional_TrabajoTerminado', models.BooleanField(default=False)),
                ('confirmacion_de_pago', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OficinaCliente.profesional')),
                ('tipoDeServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaCliente.servicio')),
            ],
        ),
    ]
