# Generated by Django 3.1.2 on 2021-01-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaCliente', '0002_orden_profesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='profesional',
        ),
        migrations.DeleteModel(
            name='Profesional',
        ),
    ]
