# Generated by Django 3.1.2 on 2021-01-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profesional', '0001_initial'),
        ('OficinaCliente', '0003_auto_20210109_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profesional.profesional'),
        ),
    ]
