# Generated by Django 3.1.2 on 2021-01-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20210112_1151'),
        ('OficinaCliente', '0004_orden_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.user'),
        ),
    ]
