# Generated by Django 3.1.2 on 2021-01-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaCliente', '0006_auto_20210121_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='resegna_Cliente',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='resegna_Profesional',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
