# Generated by Django 3.1.2 on 2021-01-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaCliente', '0007_auto_20210121_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='resegna_Cliente',
            field=models.FloatField(blank=True, default='', max_length=150, null=True),
        ),
    ]
