# Generated by Django 3.1.2 on 2021-01-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaCliente', '0008_auto_20210121_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='resegna_Cliente',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='valoracion_Cliente',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='valoracion_Profesional',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
