# Generated by Django 3.1.2 on 2021-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaCliente', '0009_auto_20210121_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='Descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servicio',
            name='Icono',
            field=models.CharField(default='', max_length=50),
        ),
    ]
