# Generated by Django 3.1.6 on 2021-02-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_user_resegna'),
        ('OficinaCliente', '0010_auto_20210126_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResegnaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('valoracion', models.FloatField(blank=True, default=0, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.user')),
            ],
        ),
    ]
