# Generated by Django 3.1.6 on 2021-02-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_user_resegna'),
        ('OficinaCliente', '0011_resegnaempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resegnaempresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Login.user'),
        ),
    ]
