# Generated by Django 3.1.6 on 2021-02-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaCliente', '0012_auto_20210207_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resegnaempresa',
            options={'ordering': ['valoracion']},
        ),
    ]
