# Generated by Django 3.1.6 on 2021-02-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaCliente', '0013_auto_20210208_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resegnaempresa',
            options={'ordering': ['-valoracion']},
        ),
    ]
